services:
  postgres:
    image: postgres:15
    container_name: ParcelDelivery_data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=142139142
      - POSTGRES_DB=ParcelDelivery
    ports:
      - "5432:5432"
    volumes:
      - ParcelDelivery_data:/var/lib/postgresql/data  

volumes:
  ParcelDelivery_data:
